version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=ProjecttWork
      SPRING_DATASOURCE_USERNAME: simon
      SPRING_DATASOURCE_PASSWORD: 9400200
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "9400200"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
